SELECT 
    ja.KONTRAK_NO,
    k.CLIENT_NAME,
    SUM(ja.ANGSURAN_PER_BULAN) AS TOTAL_ANGSURAN_JATUH_TEMPO
FROM jadwal_angsuran ja
INNER JOIN kontrak k ON ja.KONTRAK_NO = k.KONTRAK_NO
WHERE k.CLIENT_NAME = 'SUGUS' 
    AND ja.TANGGAL_JATUH_TEMPO <= '2024-08-14'
GROUP BY ja.KONTRAK_NO, k.CLIENT_NAME;