SELECT 
    ja.KONTRAK_NO,
    k.CLIENT_NAME,
    ja.ANGSURAN_KE AS INSTALLMENT_NO,
    CASE 
        WHEN ja.TANGGAL_JATUH_TEMPO <= '2024-08-14' THEN 
            DATEDIFF('2024-08-14', ja.TANGGAL_JATUH_TEMPO)
        ELSE 0
    END AS HARI_KETERLAMBATAN,
    CASE 
        WHEN ja.TANGGAL_JATUH_TEMPO <= '2024-08-14' THEN 
            ja.ANGSURAN_PER_BULAN * 0.001 * DATEDIFF('2024-08-14', ja.TANGGAL_JATUH_TEMPO)
        ELSE 0
    END AS TOTAL_DENDA
FROM jadwal_angsuran ja
INNER JOIN kontrak k ON ja.KONTRAK_NO = k.KONTRAK_NO
WHERE k.CLIENT_NAME = 'SUGUS'
    AND ja.KONTRAK_NO = 'AGR00001'
    AND ja.ANGSURAN_KE >= 6
    AND ja.TANGGAL_JATUH_TEMPO <= '2024-08-14'
ORDER BY ja.ANGSURAN_KE;